name: Deployment
on:
  push:
    branches:
      - master
    paths:
      - "src/**.md"
      - "book.toml"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup mdbook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - name: Build docs
        run: |
          mkdir -p publish/latest
          mdbook build -d publish/latest

      - uses: actions/checkout@v4
        with:
          repository: onderjan/machine-check-book-publish
          token: ${{ secrets.BOOK_PUBLISH_TOKEN }}
      - name: Publish docs in a separate repository
        run: |
          cd publish
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Documentation update"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          repository: onderjan/machine-check-book-publish
          github_token: ${{ secrets.BOOK_PUBLISH_TOKEN }}
